githubRepoOwner: Antobiotics
githubRepoName: dotfiles
githubHost: github.com
requireChecks: true
requireApproval: true
githubRemote: origin
githubBranch: master
remoteBranches: []
mergeMethod: rebase
